version: '3'

services:
  local-postgres-compose:
    #image: postgres:14.1-alpine
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - portgres-compose-network

networks:
  portgres-compose-network:
    driver: bridge
